加入message公共接口
Guakamoli/Rocket.Chat pull request #262
Opened 2021-12-22 08:17 UTC by kzyman

2021-12-22 09:26 UTC, flxxyz requested changes

2021-12-22 09:26 UTC, flxxyz commented on app/api/server/v1/chat.js
> +				coverUri = `${ serverUri }/${ coverUri }`;
这个 `serverUri` 直接写在这有问题吧，那不是所有文件资源全走 chat 了？

2021-12-23 02:39 UTC, kzyman commented on app/api/server/v1/chat.js
> +				coverUri = `${ serverUri }/${ coverUri }`;
这个在2.0主端拿的 也是  
![image](https://user-images.githubusercontent.com/11374996/147179578-7f17380b-fe9e-4293-abc3-6f1ce8a7f4e0.png)

2021-12-23 03:49 UTC, flxxyz commented on app/api/server/v1/chat.js
> +				coverUri = `${ serverUri }/${ coverUri }`;
```
coverUri.startsWith('http')
```

2021-12-23 04:27 UTC, kzyman commented on app/api/server/v1/chat.js
> +				coverUri = `${ serverUri }/${ coverUri }`;
已改

2021-12-28 09:55 UTC, flxxyz approved these changes
LGTM

2021-12-28 09:57 UTC, flxxyz commented on app/api/server/v1/chat.js
> +		}
其实有个问题，他没有视频或者图集，应该不返回结果了吧

2021-12-29 09:07 UTC, merged