fix: 给room标记主频道
Guakamoli/Rocket.Chat pull request #271
Opened 2021-12-28 08:42 UTC by lyihuan

2021-12-28 09:43 UTC, soplwang requested changes

2021-12-28 09:43 UTC, soplwang commented on app/models/server/models/Rooms.js
> +	findMainRoom(userId, type, options) {
从调用时加了 { individualMain: true } options 参数来说，这个函数还是应该叫 `findByUserIdAndType()` 才对？

2021-12-30 05:47 UTC, flxxyz approved these changes
LGTM

2021-12-30 05:51 UTC, soplwang approved these changes
LGTM

2021-12-30 05:51 UTC, merged