阿里云上传，支持多资源上传
Guakamoli/Rocket.Chat pull request #272
Opened 2021-12-29 09:05 UTC by kzyman

2021-12-30 06:05 UTC, flxxyz requested changes

2021-12-30 06:05 UTC, flxxyz commented on .husky/pre-push
> +# meteor npm run lint
删掉

2021-12-30 07:13 UTC, soplwang requested changes

2021-12-30 07:13 UTC, soplwang commented on app/api/server/v1/rooms.js
> +			if (fileItem.type.startsWith('video')) {
如果 type 是 'video-playlist/xxx' 会如何？所以最好是 startsWith('video/') 才完整

2021-12-30 07:13 UTC, soplwang commented on app/api/server/v1/rooms.js
> +					tags: [this.userId].join(','),
[id].join(',') 有点奇怪，结果不还是 id 么？

2021-12-30 08:46 UTC, kzyman commented on app/api/server/v1/rooms.js
> +			if (fileItem.type.startsWith('video')) {
没有这样的type

2021-12-30 08:46 UTC, kzyman commented on app/api/server/v1/rooms.js
> +					tags: [this.userId].join(','),
估计是格式要求

2021-12-30 10:06 UTC, soplwang requested changes

2021-12-30 10:06 UTC, soplwang commented on app/api/server/v1/rooms.js
> +			if (fileItem.type.startsWith('video')) {
这有点抬杠了。。。，依赖和信任输入数据而不是自己的逻辑不太对哈 ～

2021-12-30 10:06 UTC, soplwang commented on app/api/server/v1/rooms.js
> +API.v1.addRoute('rooms.saveUploadedFiles/:rid', { authRequired: true }, {
这个接口是 REST 这边同步多出来了的吧？

2022-01-04 07:47 UTC, kzyman commented on app/api/server/v1/rooms.js
> +			if (fileItem.type.startsWith('video')) {
改为和rocket内部一样的逻辑

2022-01-05 02:19 UTC, kzyman commented on app/api/server/v1/rooms.js
> +API.v1.addRoute('rooms.saveUploadedFiles/:rid', { authRequired: true }, {
接口已删除，合并到upload

2022-01-05 02:20 UTC, kzyman commented on app/api/server/v1/rooms.js
> +					tags: [this.userId].join(','),
已经更改该写法

2022-01-06 08:23 UTC, soplwang requested changes

2022-01-06 08:23 UTC, soplwang commented on app/api/server/v1/rooms.js
> +		if (!file?.[0]?.uri) {
API 上应当支持 field=file 单文件 和 field=file[] 多文件？

2022-01-06 11:42 UTC, soplwang approved these changes

2022-01-06 11:42 UTC, soplwang commented on app/api/server/v1/rooms.js
> +		if (!file?.[0]?.uri) {
跟上面的 L80 判断条件一样？

2022-01-06 11:56 UTC, flxxyz approved these changes
LGTM

2022-01-06 11:56 UTC, merged