修正后台上传文件到阿里云
Guakamoli/Rocket.Chat pull request #316
Opened 2022-02-08 08:26 UTC by kzyman

后台上传头像中传到阿里云

2022-02-09 08:47 UTC, flxxyz commented
通过 lint 了吗 @kzyman

2022-02-10 02:43 UTC, flxxyz requested changes

2022-02-10 02:43 UTC, flxxyz commented on app/file-upload/ufs/AliyunOSS/server.js
> +			if (!file.type.startsWith('video')) {
这块语义应该是这样呀

```js
if (file.type.startsWith('image')) {
// ...
}
```

2022-02-10 02:43 UTC, flxxyz commented on app/file-upload/ufs/AliyunOSS/server.js
> +			return this.url;
这个 `this.url` 一定有？那上面 `this.getReadStream()` 判断这个干嘛？

```js
let url = this.getFileURL(fileId);
if (!url) {
// ...
}
```

2022-02-10 02:43 UTC, flxxyz commented on app/file-upload/ufs/AliyunOSS/server.js
> +			}
整理一下代码

```js
			let ossConfig = { ...this.options.commonConfig };
			let filename = file.name;
			if (file.type.startsWith('video')) {
				// 视频需要先获取到视频的上传凭证, 然后中传给oss继续处理
				const options = {
					title: filename,
					description: `上传者ID: ${ file.userId }`,
					tags: file.userId,
					type: 'video',
					filename,
					contentType: file.type,
					contentDisposition: true,
				};
				ossConfig = Promise.await(preSignature(options));
				filename = ossConfig.filename;
				this.url = ossConfig.videoURL;
			} else {
				this.url = ossComposeURL(filename);
			}
			this.oss = OSSClient.init(ossConfig);
```

2022-02-10 02:54 UTC, kzyman commented on app/file-upload/ufs/AliyunOSS/server.js
> +			return this.url;
this.url 在上传的时候有。在没上传的时候会从 file 里面取一次，没有this.url的时候 是直接读取的时候

2022-02-10 06:04 UTC, flxxyz approved these changes

2022-02-10 06:58 UTC, flxxyz approved these changes
LGTM

2022-02-10 06:58 UTC, merged