feat: 黑名单&关键词过滤
Guakamoli/Rocket.Chat pull request #384
Opened 2022-03-14 11:09 UTC by flxxyz

2022-03-22 09:20 UTC, lyihuan requested changes

2022-03-22 09:20 UTC, lyihuan commented on app/api/server/v1/chat.js
> +			return API.v1.success({ message: 'Message not found' });
这里不对吧
API.v1.error('Message not found')

2022-03-22 09:20 UTC, lyihuan commented on app/file-upload/server/methods/sendFileMessage.ts
> +		if (attachments.filter((a) => 'image_url' in a).length > 0) {
attachments.filter((a) => 'image_url' in a).length > 0
这个没问题？？

2022-03-22 09:20 UTC, lyihuan commented on imports/kameo/server/callbacks/index.js
>  	}
if (!allowMessageTypes.includes(message.t) || message?.metadata?.category === 'system') {
  return;
}

2022-03-22 09:59 UTC, flxxyz commented on app/api/server/v1/chat.js
> +			return API.v1.success({ message: 'Message not found' });
> 这里不对吧 API.v1.error('Message not found')

对的，http 状态正常不处理，但是消息不存在，mns 服务直接跳过相关消息

2022-03-22 09:59 UTC, flxxyz commented on app/file-upload/server/methods/sendFileMessage.ts
> +		if (attachments.filter((a) => 'image_url' in a).length > 0) {
> attachments.filter((a) => 'image_url' in a).length > 0 这个没问题？？

如果不知道可以试试语法

2022-03-22 10:02 UTC, flxxyz commented on imports/kameo/server/callbacks/index.js
>  	}
> if (!allowMessageTypes.includes(message.t) || message?.metadata?.category === 'system') { return; }

功能区分开，两个条件是依赖关联的，懂？

```js
if (!allowMessageTypes.includes('activity') {
  return;
}

// activity 才有 category: 'system'
if (message?.metadata?.category === 'system') {
  return;
}
```

2022-03-23 08:52 UTC, lyihuan approved these changes

2022-03-23 08:58 UTC, flxxyz reviewed
LGTM

2022-03-23 08:58 UTC, merged