[FEAT]: Stroy 所需新增字段
Guakamoli/Rocket.Chat pull request #390
Opened 2022-03-23 08:49 UTC by kzyman

1. 新增 Room 字段storyLastMessage 存储 story 的最后一条信息
2. 新增 Room 字段slm 存储story 的最后一条信息的时间戳
3. 新增 Subscription 字段storyLs  存储 Subscription 最后已读 story 的时间

2022-03-23 09:08 UTC, flxxyz commented on server/methods/readMessages.js
> +		const { rid, t } = params;
我更倾向这样处理，好处是你那几个文件没有我们的变动

```
readMessages(rid, t) {
  check(rid, String);
  if (t) {
    check(t, String);
  }
}


```

2022-03-24 09:45 UTC, flxxyz requested changes

2022-03-24 09:45 UTC, flxxyz commented on app/api/server/v1/subscriptions.js
> +			Meteor.call('readMessages', this.bodyParams),
能不更改原有行为吗，下面连带改了好几个文件

2022-03-24 09:45 UTC, flxxyz commented on server/methods/readMessages.js
> +		const { rid, t } = params;
我更倾向这样处理，好处是你那几个文件没有我们的变动

```
readMessages(rid, t) {
  check(rid, String);
  if (t) {
    check(t, String);
  }
}
```

2022-03-25 08:10 UTC, kzyman commented on app/api/server/v1/subscriptions.js
> +		if (t) {
丑陋的一批

2022-03-25 08:24 UTC, flxxyz approved these changes
LGTM

2022-03-25 08:25 UTC, merged