feat: 支持发纯文本post
Guakamoli/Rocket.Chat pull request #457
Opened 2022-05-07 15:37 UTC by lyihuan

2022-05-08 04:28 UTC, flxxyz commented on imports/kameo/server/callbacks/index.js
> +	}
去掉

2022-05-09 03:06 UTC, flxxyz commented on imports/kameo/server/callbacks/index.js
> +			}));
你这个问题会出现 story 不能评论

2022-05-09 12:19 UTC, flxxyz submitted a review, later dismissed
LGTM

2022-05-11 20:33 UTC, soplwang requested changes, later dismissed
有些修改意见

2022-05-11 20:33 UTC, soplwang commented on app/api/server/v1/rooms.js
> +		const { postType } = fields;
如果 file[] 为空，不就是 plain 了么？是否有必要还要改变 API 增加 postType 字段？

2022-05-11 20:33 UTC, soplwang commented on app/api/server/v1/rooms.js
> +			Reflect.deleteProperty(fields, 'file[]');
直接 delete fields['file[]'] 不可以么？整个版本库搜索了下只有这一处在用 Reflect 这个高级魔法功能。。。

2022-05-11 20:33 UTC, soplwang commented on app/api/server/v1/rooms.js
> +		if (postType !== 'plain') {
理论上不需要额外判断这块，fileList 为 [] 空数组 自然就不用处理文件？

2022-05-11 20:33 UTC, soplwang commented on app/api/server/v1/rooms.js
> +			Reflect.deleteProperty(fields, 'postType');
delete fields['file[]'];

2022-05-11 20:33 UTC, soplwang commented on app/api/server/v1/rooms.js
>  			fields.t = messageType;
如果是 plain 服务端就不设置 t 为 'post' ?

2022-05-11 20:33 UTC, soplwang commented on app/api/server/v1/rooms.js
> +		} else {
感觉这个在客户端做判断为宜？

2022-05-11 20:33 UTC, soplwang commented on imports/kameo/server/callbacks/index.js
> +	const plainText = !('attachments' in message);
如果不判断是不是 post，那是不是所有没有附件的消息，都会发到推荐？私信聊天消息也发过去？感觉不太对。

要么只有 broadcastMain 为 true 的频道内的 纯文本消息 才考虑送到推荐，或者只有 t === 'post' 的纯文本消息才考虑送到推荐。。。

2022-05-12 00:44 UTC, lyihuan commented on imports/kameo/server/callbacks/index.js
> +	const plainText = !('attachments' in message);
这里前面有一个 story,post的判断
if (!allowMediaMessageTypes.includes(message.t)) {
		return message;
	}

2022-05-12 02:18 UTC, lyihuan commented on app/api/server/v1/rooms.js
>  			fields.t = messageType;
这里要改一下，去除掉，在内层要把audit给排除掉

2022-05-12 02:18 UTC, lyihuan commented on app/api/server/v1/rooms.js
> +		if (postType !== 'plain') {
这里主要的问题是:

if (!fileList) {
				if (!file) {
					throw new Meteor.Error('invalid-field');
				}
...
}

纯文本file是没有的， 直接就报错了

2022-05-12 02:54 UTC, lyihuan commented on app/api/server/v1/rooms.js
> +		} else {
这一块相当于不管是文件上传还是纯文本都是调用的这个接口

2022-05-12 04:27 UTC, flxxyz commented on imports/kameo/server/callbacks/index.js
> +	const plainText = !('attachments' in message);
> 如果不判断是不是 post，那是不是所有没有附件的消息，都会发到推荐？私信聊天消息也发过去？感觉不太对。
> 
> 要么只有 broadcastMain 为 true 的频道内的 纯文本消息 才考虑送到推荐，或者只有 t === 'post' 的纯文本消息才考虑送到推荐。。。

这个的 callbacks 只处理 post, story 类型的消息，所以这里的 plainText 是依托没有 attachments 的 post 消息

2022-05-12 06:20 UTC, flxxyz approved these changes
LGTM

2022-05-12 06:29 UTC, merged