feat:分享优化接口
Guakamoli/Rocket.Chat pull request #563
Opened 2022-07-26 06:38 UTC by Xujalg

feat:分享优化接口

2022-07-27 05:38 UTC, kzyman commented on app/api/server/v1/chat.js
> +						coverUri = `${ video_url }?x-oss-process=video/snapshot,t_0,m_fast,ar_auto,f_png`;
所有获取cover的 都可以经过一个统一的函数

2022-07-28 07:18 UTC, flxxyz requested changes

2022-07-28 07:18 UTC, flxxyz commented on app/api/server/v1/chat.js
> +				console.info('userAvatar', userAvatar);
删掉

2022-07-28 07:18 UTC, flxxyz commented on app/api/server/v1/chat.js
> +
删掉

2022-07-28 07:18 UTC, flxxyz commented on app/api/server/v1/chat.js
> +		const messagtItems = cursor.fetch();
你这个真的通过检查了？

2022-07-28 11:54 UTC, Xujalg commented on app/api/server/v1/chat.js
> +		const messagtItems = cursor.fetch();
并没有报错  难道是我关掉了。。。。

2022-07-29 03:00 UTC, flxxyz commented on app/api/server/v1/chat.js
> +		const messagtItems = cursor.fetch();
> 并没有报错 难道是我关掉了。。。。

ok

2022-07-29 03:04 UTC, flxxyz requested changes

2022-07-29 03:04 UTC, flxxyz commented on app/api/server/v1/chat.js
> +		//  凭借post信息
删掉吧

2022-07-29 05:34 UTC, lyihuan reviewed
小问题

2022-07-29 05:34 UTC, lyihuan commented on app/api/server/v1/chat.js
> +	let coverUri = attachment.video_cover_url || attachment.image_url || '';
let coverUri = attachment?.video_cover_url || attachment?.image_url || '';

2022-07-29 05:34 UTC, lyihuan commented on app/api/server/v1/chat.js
> +	if (coverUri && !coverUri.startsWith('https://')) {
if (!coverUri.startsWith('https://')) {

2022-07-29 05:34 UTC, lyihuan commented on app/api/server/v1/chat.js
> +			if (coverUri.includes('.mp4')) {
if('.mp4' === path. extname(coverUri))

path. extname: 返回路径的扩展名
文档： https://nodejs.org/docs/latest-v17.x/api/path.html#pathextnamepath

2022-07-29 05:34 UTC, lyihuan commented on app/api/server/v1/chat.js
> +		const t = msg?.attachments[0].image_type || msg?.attachments[0].video_type || null;
const t = msg?.attachments[0].image_type || msg?.attachments[0].video_type || null;

为什么这里需要  || null

2022-07-29 05:51 UTC, flxxyz approved these changes
LGTM

2022-07-29 05:52 UTC, merged