fix:修改用户信息 同步推荐系统
Guakamoli/Rocket.Chat pull request #588
Opened 2022-08-17 02:15 UTC by Xujalg

fix:修改用户信息 同步推荐系统

2022-08-18 02:38 UTC, lyihuan requested changes
有些许变更

2022-08-18 02:38 UTC, lyihuan commented on app/api/server/v1/users.js
> +		});
```js
if (Array.isArray(this?.bodyParams?.data?.labels)) {
  Meteor.call('kameoRocketmqSendGorseUser', {
    labels: this?.bodyParams?.data?.labels,
    userId: this?.bodyParams?.userId,
  });
}
```

2022-08-18 02:38 UTC, lyihuan commented on app/api/server/v1/users.js
> +		});
确认一下这里是否可以传入空数组，如果不能的话if中需要判断一下labels长度大于0

2022-08-18 02:38 UTC, lyihuan commented on imports/kameo/server/methods/rocketmq.js
> +	gorseUser: process.env.MQ_TOPIC_ID_GORSE,
updateGorseUser: process.env.MQ_TOPIC_ID_GORSE

2022-08-18 02:38 UTC, lyihuan commented on imports/kameo/server/methods/rocketmq.js
> +	await rocketmqSend(topicIds.gorseUser, JSON.stringify(payload), tag, 'rocketchat');
await rocketmqSend(topicIds.updateGorseUser, JSON.stringify(payload), tag, 'rocketchat');
Member

2022-08-18 03:18 UTC, Xujalg commented on app/api/server/v1/users.js
> +		});
可以传空 recomend 那边 空数组 默认填入web3

2022-08-18 06:45 UTC, flxxyz commented on app/api/server/v1/users.js
> +		});
> 可以传空 recomend 那边 空数组 默认填入web3

是两个问题，还有没有更新的时候不处理，不发送MQ消息

2022-08-19 02:15 UTC, lyihuan approved these changes
LGTM

2022-08-19 02:17 UTC, flxxyz commented on app/api/server/v1/users.js
> +				labels: this?.bodyParams?.data?.labels || [],
```js
{
labels: this.bodyParams.data.labels
// ...
}
```

2022-08-19 02:39 UTC, merged